Month7/step1
vveb/react-stellar-burger pull request #1
Opened 2023-06-27 15:26 UTC by vveb

Выполнена верстка всех компонентов с использованием React
Компонент BurgerIngredients декомпозирован на два каскадных компонента: CardList (список ингредиентов определенного типа) и IngredientCard (карточка одного ингредиента в списке)

Реализована простая логика:
- добавления ингредиентов в заказ (по клику на ингредиент)
- подсчета количества добавленных ингредиентов на основе списка в заказе
- подсчета итоговой стоимости

Добавлены валидаторы пропсов

Булочки выбраны по дефолту изначально, можно менять

2023-06-27 17:56 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Хорошая работа с `propTypes`

Необходимо исправить:
- У полей объекта `ingredientPropType ` так же должны быть `isRequired`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-27 17:56 UTC, andryxxa93 commented on src/utils/prop-types.js
> +  _id: PropTypes.string,
**Необходимо исправить**
У полей объекта так же необходимо ставить `isRequired`

2023-06-27 17:56 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <Tab value="buns" active={current === 'buns'} onClick={setCurrent}>
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-06-28 15:47 UTC, vveb commented
**После ревью**

1. Поправлены PropTypes, добавлено свойство isRequired.
2. Улучшен код:
> - пропс ingredientList убран с помощью контекста, чтобы не прокидывать его вглубь и не растить код;
> - изменена логика работы счетчиков ингредиентов;
> - реализованы функции добавления/удаления ингредиентов в/из конструктор(а);
> - изменена логика подсчета итоговой стоимости.
3. Добавлен интерактивный скролл для списка ингредиентов по нажатию кнопок меню.
4. Создан компонент TotalPrice, в который вынесена логика подсчета итоговой стоимости и разметка

2023-06-28 15:47 UTC, vveb commented on src/utils/prop-types.js
> +  _id: PropTypes.string,
Сделано

2023-06-28 15:48 UTC, vveb commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <Tab value="buns" active={current === 'buns'} onClick={setCurrent}>
Сделано

2023-06-28 16:47 UTC, andryxxa93 commented
Промежуточная работа принята! Вы может приступать к финальному этапу сдачи работы. 
Удачи!

2023-07-10 13:03 UTC, merged